sudo: false
language: erlang
env:
  global:
    - ELIXIR="v1.0.2"
    - MIX_ENV=test
otp_release:
  - 17.0
  - 17.3
before_install:
  - mkdir -p vendor/elixir
  - wget -q https://github.com/elixir-lang/elixir/releases/download/$ELIXIR/Precompiled.zip
  - unzip -qq Precompiled.zip -d vendor/elixir
  - export PATH="$PATH:$PWD/vendor/elixir/bin"
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get
script:
  - mix test
after_success:
  - mix compile && mix coveralls.travis
notifications:
  recipients:
    - b.gianfo@gmail.com
