sudo: false
language: elixir
env:
  global:
    - MIX_ENV=test

before_script:
  - mix local.hex --force
  - mix deps.get
script:
  - mix test
after_success:
  - mix compile && mix coveralls.travis
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - b.gianfo@gmail.com
